name: PR Required Tasks

on:
  pull_request:
    types: [opened, edited]

jobs:

  task-check:
    runs-on: ubuntu-latest
    name: Required Tasks Status Check
    steps:
      - name: Check for Incomplete Required Tasks
        uses: meagerfindings/PR-required-tasks@v0.0.13
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
